### ISSUE TITLE
电脑版本next不能点击

### ISSUE THREAD

**Issue by chai2010** [gopl-zh/gopl-zh.github.com#107]
提示：哪一章节的问题，建议如何修改

**Comment by Asakijz** [comment]
你好，这个应该是因为 `z-index` 的问题所导致的，`pagetoc` 被置于最顶层（目前读到5.9 panic异常 小节，从首节至此均无法通过 next 跳转下一节）

将下列标签的 `z-index `样式取消后即可正常跳转
<nav class="pagetoc"></nav>

**Comment by Asakijz** [comment]
感谢作者大大们的翻译

**Comment by chai2010** [comment]
能帮忙修复下吗？另外目录好折叠吗？感谢

**Comment by Asakijz** [comment]
目录折叠目前看来没有问题，z-index 注释掉后 next 跳转应该就可以正常点击了

**Comment by chai2010** [comment]
> 目录折叠目前看来没有问题，z-index 注释掉后 next 跳转应该就可以正常点击了

已经修复，感谢
